"""baseline

Revision ID: 61335850cc58
Revises: afd5547d26ca
Create Date: 2026-02-08 10:18:32.858194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61335850cc58'
down_revision: Union[str, Sequence[str], None] = 'afd5547d26ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dividends', sa.Column('div_type', sa.String(length=255), nullable=True))
    op.add_column('dividends', sa.Column('company_type', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_dividends_symbol_exdate'), table_name='dividends')
    op.create_index(op.f('ix_dividends_company_type'), 'dividends', ['company_type'], unique=False)
    op.create_index(op.f('ix_dividends_div_type'), 'dividends', ['div_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dividends_div_type'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_company_type'), table_name='dividends')
    op.create_index(op.f('ix_dividends_symbol_exdate'), 'dividends', ['symbol', 'dividend_ex_date'], unique=True)
    op.drop_column('dividends', 'company_type')
    op.drop_column('dividends', 'div_type')
    # ### end Alembic commands ###
