"""exchange

Revision ID: 8d6df10a654f
Revises: 20a237b88dda
Create Date: 2026-02-08 18:01:34.996929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6df10a654f'
down_revision: Union[str, Sequence[str], None] = '20a237b88dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbols',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('symbol2', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('displaySymbol', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('figi', sa.String(), nullable=False),
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('mic', sa.String(), nullable=False),
    sa.Column('shareClassFIGI', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_id'), 'symbols', ['id'], unique=False)
    op.create_index(op.f('ix_symbols_symbol'), 'symbols', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symbols_symbol'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_id'), table_name='symbols')
    op.drop_table('symbols')
    # ### end Alembic commands ###
