"""initial schema

Revision ID: 90dcdca1c14e
Revises: 4afe3d9debf6
Create Date: 2026-02-05 09:25:39.197887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '90dcdca1c14e'
down_revision: Union[str, Sequence[str], None] = '4afe3d9debf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dividend_chunks_3072',
    sa.Column('embedding', Vector(dim=3072), nullable=True),
    sa.Column('div_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dividend_chunks_3072_div_chunk', 'dividend_chunks_3072', ['div_id', 'chunk_index'], unique=True)
    op.create_index(op.f('ix_dividend_chunks_3072_id'), 'dividend_chunks_3072', ['id'], unique=False)
    op.create_index(op.f('ix_dividend_chunks_3072_note'), 'dividend_chunks_3072', ['note'], unique=False)
    op.create_table('dividend_chunks_768',
    sa.Column('embedding', Vector(dim=768), nullable=True),
    sa.Column('div_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dividend_chunks_768_div_chunk', 'dividend_chunks_768', ['div_id', 'chunk_index'], unique=True)
    op.create_index(op.f('ix_dividend_chunks_768_id'), 'dividend_chunks_768', ['id'], unique=False)
    op.create_index(op.f('ix_dividend_chunks_768_note'), 'dividend_chunks_768', ['note'], unique=False)
    op.drop_index(op.f('idx_wages_er_code_code_re'), table_name='canada_wage_2012_2025')
    op.drop_index(op.f('idx_wages_noc_cnp'), table_name='canada_wage_2012_2025')
    op.drop_index(op.f('idx_wages_noc_prov'), table_name='canada_wage_2012_2025')
    op.drop_index(op.f('idx_wages_prov'), table_name='canada_wage_2012_2025')
    op.drop_index(op.f('idx_wages_reference_period'), table_name='canada_wage_2012_2025')
    op.drop_index(op.f('ix_canada_wage_2012_2025_classification'), table_name='canada_wage_2012_2025')
    op.drop_index(op.f('ix_canada_wage_2012_2025_id'), table_name='canada_wage_2012_2025')
    op.drop_table('canada_wage_2012_2025')
    op.drop_index(op.f('ix_dividend_chunks_div_chunk'), table_name='dividend_chunks_1536')
    op.drop_index(op.f('ix_dividend_chunks_id'), table_name='dividend_chunks_1536')
    op.drop_index(op.f('ix_dividend_chunks_note'), table_name='dividend_chunks_1536')
    op.create_index('ix_dividend_chunks_1536_div_chunk', 'dividend_chunks_1536', ['div_id', 'chunk_index'], unique=True)
    op.create_index(op.f('ix_dividend_chunks_1536_id'), 'dividend_chunks_1536', ['id'], unique=False)
    op.create_index(op.f('ix_dividend_chunks_1536_note'), 'dividend_chunks_1536', ['note'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dividend_chunks_1536_note'), table_name='dividend_chunks_1536')
    op.drop_index(op.f('ix_dividend_chunks_1536_id'), table_name='dividend_chunks_1536')
    op.drop_index('ix_dividend_chunks_1536_div_chunk', table_name='dividend_chunks_1536')
    op.create_index(op.f('ix_dividend_chunks_note'), 'dividend_chunks_1536', ['note'], unique=False)
    op.create_index(op.f('ix_dividend_chunks_id'), 'dividend_chunks_1536', ['id'], unique=False)
    op.create_index(op.f('ix_dividend_chunks_div_chunk'), 'dividend_chunks_1536', ['div_id', 'chunk_index'], unique=True)
    op.create_table('canada_wage_2012_2025',
    sa.Column('noc_cnp', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('noc_title_eng', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('noc_title_fra', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('prov', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('er_code_code_re', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('er_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nom_re', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('low_wage_salaire_minium', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('median_wage_salaire_median', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('high_wage_salaire_maximal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_wage_salaire_moyen', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quartile1_wage_salaire_quartile1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quartile3_wage_salaire_quartile3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('annual_wage_flag_salaire_annuel', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('source2025_nhq', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data_source_e', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data_source_f', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('reference_period', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('revision_date_date_revision', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('wage_comment_e', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wage_comment_f', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('employeeswithnonwagebenefit_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('classification', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('canada_wage_2012_2025_pkey'))
    )
    op.create_index(op.f('ix_canada_wage_2012_2025_id'), 'canada_wage_2012_2025', ['id'], unique=False)
    op.create_index(op.f('ix_canada_wage_2012_2025_classification'), 'canada_wage_2012_2025', ['classification'], unique=False)
    op.create_index(op.f('idx_wages_reference_period'), 'canada_wage_2012_2025', ['reference_period'], unique=False)
    op.create_index(op.f('idx_wages_prov'), 'canada_wage_2012_2025', ['prov'], unique=False)
    op.create_index(op.f('idx_wages_noc_prov'), 'canada_wage_2012_2025', ['noc_cnp', 'prov'], unique=False)
    op.create_index(op.f('idx_wages_noc_cnp'), 'canada_wage_2012_2025', ['noc_cnp'], unique=False)
    op.create_index(op.f('idx_wages_er_code_code_re'), 'canada_wage_2012_2025', ['er_code_code_re'], unique=False)
    op.drop_index(op.f('ix_dividend_chunks_768_note'), table_name='dividend_chunks_768')
    op.drop_index(op.f('ix_dividend_chunks_768_id'), table_name='dividend_chunks_768')
    op.drop_index('ix_dividend_chunks_768_div_chunk', table_name='dividend_chunks_768')
    op.drop_table('dividend_chunks_768')
    op.drop_index(op.f('ix_dividend_chunks_3072_note'), table_name='dividend_chunks_3072')
    op.drop_index(op.f('ix_dividend_chunks_3072_id'), table_name='dividend_chunks_3072')
    op.drop_index('ix_dividend_chunks_3072_div_chunk', table_name='dividend_chunks_3072')
    op.drop_table('dividend_chunks_3072')
    # ### end Alembic commands ###
