"""update base

Revision ID: afd5547d26ca
Revises: c9e993a1e138
Create Date: 2026-02-05 17:58:04.150590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afd5547d26ca'
down_revision: Union[str, Sequence[str], None] = 'c9e993a1e138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dividend_chunks_1536', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dividend_chunks_3072', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dividend_chunks_768', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dividends', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dividends', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dividend_chunks_768', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dividend_chunks_3072', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dividend_chunks_1536', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
