"""update base

Revision ID: c9e993a1e138
Revises: 90dcdca1c14e
Create Date: 2026-02-05 16:54:13.626513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e993a1e138'
down_revision: Union[str, Sequence[str], None] = '90dcdca1c14e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dividend_chunks_1536', sa.Column('status', sa.String(), nullable=True))
    op.add_column('dividend_chunks_1536', sa.Column('description', sa.String(), nullable=False))
    op.drop_index(op.f('ix_dividend_chunks_1536_note'), table_name='dividend_chunks_1536')
    op.drop_column('dividend_chunks_1536', 'note')
    op.add_column('dividend_chunks_3072', sa.Column('status', sa.String(), nullable=True))
    op.add_column('dividend_chunks_3072', sa.Column('description', sa.String(), nullable=False))
    op.drop_index(op.f('ix_dividend_chunks_3072_note'), table_name='dividend_chunks_3072')
    op.drop_column('dividend_chunks_3072', 'note')
    op.add_column('dividend_chunks_768', sa.Column('status', sa.String(), nullable=True))
    op.add_column('dividend_chunks_768', sa.Column('description', sa.String(), nullable=False))
    op.drop_index(op.f('ix_dividend_chunks_768_note'), table_name='dividend_chunks_768')
    op.drop_column('dividend_chunks_768', 'note')
    op.add_column('dividends', sa.Column('status', sa.String(), nullable=True))
    op.add_column('dividends', sa.Column('description', sa.String(), nullable=False))
    op.drop_index(op.f('ix_dividends_note'), table_name='dividends')
    op.drop_column('dividends', 'note')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dividends', sa.Column('note', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_dividends_note'), 'dividends', ['note'], unique=False)
    op.drop_column('dividends', 'description')
    op.drop_column('dividends', 'status')
    op.add_column('dividend_chunks_768', sa.Column('note', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_dividend_chunks_768_note'), 'dividend_chunks_768', ['note'], unique=False)
    op.drop_column('dividend_chunks_768', 'description')
    op.drop_column('dividend_chunks_768', 'status')
    op.add_column('dividend_chunks_3072', sa.Column('note', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_dividend_chunks_3072_note'), 'dividend_chunks_3072', ['note'], unique=False)
    op.drop_column('dividend_chunks_3072', 'description')
    op.drop_column('dividend_chunks_3072', 'status')
    op.add_column('dividend_chunks_1536', sa.Column('note', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_dividend_chunks_1536_note'), 'dividend_chunks_1536', ['note'], unique=False)
    op.drop_column('dividend_chunks_1536', 'description')
    op.drop_column('dividend_chunks_1536', 'status')
    # ### end Alembic commands ###
